// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: transactions.sql

package db

import (
	"context"
)

const buyItem = `-- name: BuyItem :exec
INSERT INTO transactions (
  item_id, buyer_email
) VALUES (
  $1, $2
)
`

type BuyItemParams struct {
	ItemID     int64  `json:"itemID"`
	BuyerEmail string `json:"buyerEmail"`
}

func (q *Queries) BuyItem(ctx context.Context, arg BuyItemParams) error {
	_, err := q.db.ExecContext(ctx, buyItem, arg.ItemID, arg.BuyerEmail)
	return err
}
