CREATE TABLE IF NOT EXISTS users (
  email VARCHAR(300) NOT NULL UNIQUE PRIMARY KEY,
  name VARCHAR(300) NOT NULL,
  join_year INTEGER NOT NULL,
  profile_picture_url VARCHAR(300) NOT NULL,
  hostel VARCHAR(300) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS google_tokens (
  id BIGSERIAL PRIMARY KEY,
  user_email VARCHAR(300) UNIQUE NOT NULL REFERENCES users(email) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL,
  refresh_token VARCHAR(300) NOT NULL,
  access_token VARCHAR(300) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  token_type VARCHAR(150) NOT NULL
);
